### ISSUE TITLE
default task run time doesn't look quite right

### ISSUE THREAD

**Issue by danmarsden** [oliviervalentin/moodle-report_coursemanager#37]
https://github.com/oliviervalentin/moodle-report_coursemanager/blob/main/db/tasks.php#L39-L45

I think you are trying to make it run every 30min, but you've put the value in the day field? - I'm not sure what that would actually do (maybe it actually does what you are wanting it to?) but it looks wrong to me so you might want to check that.... :-)

**Comment by oliviervalentin** [comment]
Hi @danmarsden ,
not an error ! :)
I'm working for a direct application of this plugin in my university. The goal is to send regularly a mail for each teacher, as a summary of all the courses they manage, and if some of these courses are concerned by reports (heavy courses, courses without students...). 
But we don't want to send it every week, or even every 30 minutes ! :) We have planned that a monthly mail is enough, to give them a preview of their courses and reports related to each. That's why the default parameter for this mailing is every 30 days.

Is this delay not recommended by Moodle ?

Best regards,
Olivier

**Comment by danmarsden** [comment]
nah - it's the minute and hour being set to "*" that is confusing me... the way my brain reads that is...

every 30 days, run the task every minute during that day 

that might not actually be what moodle decides to do in this case, but it's probably worth checking to see if you shuold have fixed values in the minute and hour fields (or set to "R" to make Moodle choose a random time and minute to run it.

**Comment by oliviervalentin** [comment]
Fixed default settings for task scheduling : now mailing will be send every 30 days, at 4AM. Minutes has been set to R as mentioned.
Old settings with * for days and minutes would have send mailing every minute for scheduled day !! Thank you very much for preventing this mailing disaster !

**Comment by danmarsden** [comment]
no worries - I wasn't sure if Moodle would interpret it that way or not but good to know!
