### ISSUE TITLE
Unsupported operand types: string / int

### ISSUE THREAD

**Issue by mamaeves** [oliviervalentin/moodle-report_coursemanager#56]
I have empty config values

- last_access_teacher
- last_access_student

When I open page /report/coursemanager/view.php I get Unsupported operand types: string / int exception on lines
262 and 276

**Comment by oliviervalentin** [comment]
Hi @mamaeves !

These two config values must be set in the plugin settings (Site administration > Plugins > Reports > Course Manager).  Without these, Course Manager can't calculate reports to set if a course has no visits since the defined number of days.

Visits are a good indicator to see if a course is stuill alive or not, so these params are necessary to make this plugin work. But I admit that no values generates an error ! I will add a precontrol to check if all settings are ok. I tag your ticket as "enhancement".

Olivier

**Comment by oliviervalentin** [comment]
OK, this problem is fixed in new version I just released at the moment.
I keep this ticket open - I'd like to work on possibility to enable/disable reports, this will too avoid errors when settings are not defined correctly.
